[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[unstable]
build-std = ["alloc", "core"]

[env]
DEFMT_LOG = "debug"
